services:
  localdb:
    container_name: sbmdb
    image: mysql:8.0
    ports:
      - 3310:3306
    expose:
      - 3310
    environment:
      MYSQL_ROOT_PASSWORD: TestdbRoot
      MYSQL_DATABASE: sbmdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
      - --default-time-zone=Asia/Seoul

    volumes:
      - ./mysql:/var/lib/mysql
